AWSTemplateFormatVersion: '2011-09-09'
Description: ECS Service Template
Parameters:
  EnvType:
    Type: String
  ContainerImage:
    Type: String
  Subnets:
    Type: List<String>
  AlbSG:
    Type: String
  ServiceName:
    Type: String
Resources:
  TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ServiceName}-${EnvType}
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: arn:aws:iam::123456789012:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 8080
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${ServiceName}-${EnvType}
      Cluster: !ImportValue !Sub ${EnvType}-cluster-name
      TaskDefinition: !Ref TaskDef
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref Subnets
          SecurityGroups: [!Ref AlbSG]
          AssignPublicIp: ENABLED
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: 8080
          TargetGroupArn: arn:aws:elasticloadbalancing:ap-south-1:xxxx:targetgroup/dummy
