AWSTemplateFormatVersion: '2010-09-09'
Description: Create a basic Amazon ECR repository

Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-b-ecr-repo
      ImageScanningConfiguration:
        scanOnPush: true
      Tags:
        - Key: Name
          Value: my-b-ecr-repo
