AWSTemplateFormatVersion: '2010-09-10'
Description: Create an ECR repository based on the environment (dev/qaa/prod)

Parameters:
  EnvType:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - qaa
      - prod
    Default: dev

  RepoName:
    Type: String
    Description: Base name of the ECR repository
    Default: my-app

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${RepoName}-${EnvType}-shared1"
      ImageScanningConfiguration:
        scanOnPush: true
      Tags:
        - Key: Name
          Value: !Sub "${RepoName}-${EnvType}-shared1-tag"
        - Key: Environment
          Value: !Ref EnvType
